In [49]:
import pandas as pd

# Replace 'your_excel_file.xlsx' with the path to your Excel file
data = pd.read_excel(r"C:\Users\shres\Downloads\TUFTS.xlsx")

# Now 'df' is your DataFrame containing the data from the Excel file
data

,UNITED HEALTHCARE UNDERWRITING FULLY INSURED APPROVAL FORM - For Internal Use Only,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,FINAL SOLD RATES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AGE/SEX,NaN,2.16,NaN,NaN,NaN,NaN,NaN,NaN
2,ORIGINATING SITE,NaN,Rhode Island,NaN,NaN,NaN,EFFECTIVE DATE,1/1/2024,THROUGH,12/31/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENEFIT ALLY QUOTED,NaN,N
3,GROUP NAME,NaN,GREATER NOIDA MENTAL HEALTH CENTER,NaN,NaN,NaN,ACCOUNT EXECUTIVE,Bryan Cranston,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NEW BUSINESS/RENEWAL,NaN,NEW BUSINESS,NaN,NaN,NaN,UNDERWRITER,Kristen Bell,NaN,NaN,NaN,HP ALLIANCE GROUP:,NaN,No,NaN,NaN,NaN,SPECIALITY COMMISSION,NaN,0.1
5,CARRIER REPLACE Y/N:,NaN,Y,NaN,NaN,NaN,COMMISSION,$31.00 PEM,SERVICE FEE,NaN,NaN,# OF SITUS STATES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MULTI-SITE Y/N:,NaN,Y,NaN,NaN,NaN,COMMISSION NOTES,NaN,NaN,NaN,NaN,SECOND SITUS STATE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,DATE,NaN,10/4/2023,NaN,NaN,NaN,AGGREGATED GRP #s,NaN,NaN,NaN,NaN,HP RATE TIER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,COMPOSITE RENEWAL ACTION,NaN,NaN,NaN,NaN,NaN,SUBJECT TO MED U/W,___ YES,___ NO,NaN,NaN,CASE CHARACTERISTIC SCORE,NaN,15,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,OPTION 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,PRIMARY/SOLD PLAN,NaN,NaN,NaN,NaN,NaN,NaN,Premium Incl.,Premium,NaN,NaN,NaN,NaN,NaN
12,Situs State,NH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Subs,Mbrs,"Comm, Fees",Less Fees,NaN,NaN,NaN,NaN,NaN
13,License (HMO vs Ins Co),EPO,NaN,NaN,Benefit Plan,NaN,CPIJ Mod,(Granite Advantage EPO OA),NaN,NaN,EE Only,87,NaN,$ 886.06,NaN,NaN,NaN,NaN,NaN,NaN
14,Sites(s)/Network(s),National- Excl. OOA,NaN,NaN,In Network Copays,NaN,"PCP $10/$10, SPC $25/$25, OP $250/D&C, IP D&C,...",NaN,NaN,NaN,EE + Spouse,25,NaN,$ 1064.07,NaN,NaN,NaN,NaN,NaN,NaN
15,Platform/Product,CiTrus,Gravel Advantage EPO,NaN,In Net Ded/Coins/OOP,NaN,"Ded $5,000/$10,000 (Emb), Coins 80%, OOP $6,00...",NaN,NaN,NaN,EE + Childern,38,NaN,$ 2035.58,NaN,NaN,NaN,NaN,NaN,NaN
16,Multiple Plan Offering:,Dual Option with 2,NaN,NaN,Out of Network,NaN,"Ded N/A, Coins N/A, OOP N/A",NaN,NaN,NaN,Family,37,NaN,$ 1037.07,NaN,NaN,NaN,NaN,NaN,NaN
17,Coverage for Retirees:,N,Min Value,Pass,Other/Riders,NaN,"UHCR Prem,",NaN,NaN,NaN,Totals/PMPM,170,47,$ 103.487,NaN,NaN,NaN,NaN,NaN,NaN
18,Legal Entity,THFIC,NaN,NaN,Drug Benefit,NaN,"$3/$33/$50, 2 MO (Adv PDL)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,Rating Group,NaN,Rx Plan: TH15-INT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,OPTION 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,PRIMARY/SOLD PLAN,NaN,NaN,NaN,NaN,NaN,NaN,Premium Incl.,Premium,NaN,NaN,NaN,NaN,NaN
24,Situs State,NH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Subs,Mbrs,"Comm, Fees",Less Fees,NaN,NaN,NaN,NaN,NaN
25,License (HMO vs Ins Co),EPO,NaN,NaN,Benefit Plan,NaN,CPIJ Mod,(Granite Advantage EPO OA),NaN,NaN,EE Only,87,NaN,$ 886.06,NaN,NaN,NaN,NaN,NaN,NaN
26,Sites(s)/Network(s),National- Excl. OOA,NaN,NaN,In Network Copays,NaN,"PCP $20/$20, SPC $35/$35, OP $350/D&C, IP D&C,...",NaN,NaN,NaN,EE + Spouse,25,NaN,$ 1064.07,NaN,NaN,NaN,NaN,NaN,NaN
27,Platform/Product,CiTrus,Gravel Advantage EPO Saver,NaN,In Net Ded/Coins/OOP,NaN,"Ded $6,000/$12,000 (Emb), Coins 90%, OOP $7,00...",NaN,NaN,NaN,EE + Childern,38,NaN,$ 2035.58,NaN,NaN,NaN,NaN,NaN,NaN
28,Multiple Plan Offering:,Dual Option with 2,NaN,NaN,Out of Network,NaN,"Ded N/A, Coins N/A, OOP N/A",NaN,NaN,NaN,Family,37,NaN,$ 1037.07,NaN,NaN,NaN,NaN,NaN,NaN
29,Coverage for Retirees:,N,Min Value,Pass,Other/Riders,NaN,"UHCR Prem,",NaN,NaN,NaN,Totals/PMPM,170,47,$ 103.487,NaN,NaN,NaN,NaN,NaN,NaN
30,Legal Entity,THFIC,NaN,NaN,Drug Benefit,NaN,"$4/$44/$60, 2 MO (Adv PDL)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,Rating Group,NaN,Rx Plan: TH15-INT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,GRAND TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,Premium Incl.,Premium,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Subs,Mbrs,"Comm, Fees",Less Fees,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EE Only,87,NaN,$ 886.06,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EE + Spouse,25,NaN,$ 1064.07,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EE + Childern,38,NaN,$ 2035.58,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Family,37,NaN,$ 1037.07,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Totals/PMPM,170,47,$ 103.487,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,WER HGFDD dfghjl hbvc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,"# Extracting the words ""PCP"", ""SPC"", ""UC"", ""ER...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,"filtered_df.insert(loc=1, column='Type', value...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,"# Fill NaN values in the ""Type"" column with a ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,"filtered_df['Type'].fillna('', inplace=True)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,# Display the modified DataFrame,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,print(filtered_df),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
# Iterate through the DataFrame rows
for index, row in data.iterrows():
    for col in range(len(row)):
        # If the cell contains "PRIMARY/SOLD PLAN"
        if row[col] == "PRIMARY/SOLD PLAN":
            # Fill all cells to the left with the value "PRIMARY/SOLD PLAN"
            for i in range(col - 1, -1, -1):
                data.iloc[index, i] = row[col]

In [51]:
data

,UNITED HEALTHCARE UNDERWRITING FULLY INSURED APPROVAL FORM - For Internal Use Only,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,FINAL SOLD RATES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AGE/SEX,NaN,2.16,NaN,NaN,NaN,NaN,NaN,NaN
2,ORIGINATING SITE,NaN,Rhode Island,NaN,NaN,NaN,EFFECTIVE DATE,1/1/2024,THROUGH,12/31/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENEFIT ALLY QUOTED,NaN,N
3,GROUP NAME,NaN,GREATER NOIDA MENTAL HEALTH CENTER,NaN,NaN,NaN,ACCOUNT EXECUTIVE,Bryan Cranston,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NEW BUSINESS/RENEWAL,NaN,NEW BUSINESS,NaN,NaN,NaN,UNDERWRITER,Kristen Bell,NaN,NaN,NaN,HP ALLIANCE GROUP:,NaN,No,NaN,NaN,NaN,SPECIALITY COMMISSION,NaN,0.1
5,CARRIER REPLACE Y/N:,NaN,Y,NaN,NaN,NaN,COMMISSION,$31.00 PEM,SERVICE FEE,NaN,NaN,# OF SITUS STATES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MULTI-SITE Y/N:,NaN,Y,NaN,NaN,NaN,COMMISSION NOTES,NaN,NaN,NaN,NaN,SECOND SITUS STATE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,DATE,NaN,10/4/2023,NaN,NaN,NaN,AGGREGATED GRP #s,NaN,NaN,NaN,NaN,HP RATE TIER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,COMPOSITE RENEWAL ACTION,NaN,NaN,NaN,NaN,NaN,SUBJECT TO MED U/W,___ YES,___ NO,NaN,NaN,CASE CHARACTERISTIC SCORE,NaN,15,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,OPTION 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,NaN,NaN,NaN,NaN,NaN,NaN,Premium Incl.,Premium,NaN,NaN,NaN,NaN,NaN
12,Situs State,NH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Subs,Mbrs,"Comm, Fees",Less Fees,NaN,NaN,NaN,NaN,NaN
13,License (HMO vs Ins Co),EPO,NaN,NaN,Benefit Plan,NaN,CPIJ Mod,(Granite Advantage EPO OA),NaN,NaN,EE Only,87,NaN,$ 886.06,NaN,NaN,NaN,NaN,NaN,NaN
14,Sites(s)/Network(s),National- Excl. OOA,NaN,NaN,In Network Copays,NaN,"PCP $10/$10, SPC $25/$25, OP $250/D&C, IP D&C,...",NaN,NaN,NaN,EE + Spouse,25,NaN,$ 1064.07,NaN,NaN,NaN,NaN,NaN,NaN
15,Platform/Product,CiTrus,Gravel Advantage EPO,NaN,In Net Ded/Coins/OOP,NaN,"Ded $5,000/$10,000 (Emb), Coins 80%, OOP $6,00...",NaN,NaN,NaN,EE + Childern,38,NaN,$ 2035.58,NaN,NaN,NaN,NaN,NaN,NaN
16,Multiple Plan Offering:,Dual Option with 2,NaN,NaN,Out of Network,NaN,"Ded N/A, Coins N/A, OOP N/A",NaN,NaN,NaN,Family,37,NaN,$ 1037.07,NaN,NaN,NaN,NaN,NaN,NaN
17,Coverage for Retirees:,N,Min Value,Pass,Other/Riders,NaN,"UHCR Prem,",NaN,NaN,NaN,Totals/PMPM,170,47,$ 103.487,NaN,NaN,NaN,NaN,NaN,NaN
18,Legal Entity,THFIC,NaN,NaN,Drug Benefit,NaN,"$3/$33/$50, 2 MO (Adv PDL)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,Rating Group,NaN,Rx Plan: TH15-INT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,OPTION 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,NaN,NaN,NaN,NaN,NaN,NaN,Premium Incl.,Premium,NaN,NaN,NaN,NaN,NaN
24,Situs State,NH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Subs,Mbrs,"Comm, Fees",Less Fees,NaN,NaN,NaN,NaN,NaN
25,License (HMO vs Ins Co),EPO,NaN,NaN,Benefit Plan,NaN,CPIJ Mod,(Granite Advantage EPO OA),NaN,NaN,EE Only,87,NaN,$ 886.06,NaN,NaN,NaN,NaN,NaN,NaN
26,Sites(s)/Network(s),National- Excl. OOA,NaN,NaN,In Network Copays,NaN,"PCP $20/$20, SPC $35/$35, OP $350/D&C, IP D&C,...",NaN,NaN,NaN,EE + Spouse,25,NaN,$ 1064.07,NaN,NaN,NaN,NaN,NaN,NaN
27,Platform/Product,CiTrus,Gravel Advantage EPO Saver,NaN,In Net Ded/Coins/OOP,NaN,"Ded $6,000/$12,000 (Emb), Coins 90%, OOP $7,00...",NaN,NaN,NaN,EE + Childern,38,NaN,$ 2035.58,NaN,NaN,NaN,NaN,NaN,NaN
28,Multiple Plan Offering:,Dual Option with 2,NaN,NaN,Out of Network,NaN,"Ded N/A, Coins N/A, OOP N/A",NaN,NaN,NaN,Family,37,NaN,$ 1037.07,NaN,NaN,NaN,NaN,NaN,NaN
29,Coverage for Retirees:,N,Min Value,Pass,Other/Riders,NaN,"UHCR Prem,",NaN,NaN,NaN,Totals/PMPM,170,47,$ 103.487,NaN,NaN,NaN,NaN,NaN,NaN
30,Legal Entity,THFIC,NaN,NaN,Drug Benefit,NaN,"$4/$44/$60, 2 MO (Adv PDL)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,Rating Group,NaN,Rx Plan: TH15-INT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,GRAND TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,Premium Incl.,Premium,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Subs,Mbrs,"Comm, Fees",Less Fees,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EE Only,87,NaN,$ 886.06,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EE + Spouse,25,NaN,$ 1064.07,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EE + Childern,38,NaN,$ 2035.58,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Family,37,NaN,$ 1037.07,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Totals/PMPM,170,47,$ 103.487,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,WER HGFDD dfghjl hbvc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,"# Extracting the words ""PCP"", ""SPC"", ""UC"", ""ER...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,"filtered_df.insert(loc=1, column='Type', value...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,"# Fill NaN values in the ""Type"" column with a ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,"filtered_df['Type'].fillna('', inplace=True)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,# Display the modified DataFrame,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,print(filtered_df),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [52]:
import numpy as np
import re
# Extract unique options from the DataFrame
unique_options = set()

for index, row in data.iterrows():
    for cell in row:
        if isinstance(cell, str):  # Check if the cell is a string
            options = re.findall(r'OPTION \d+', cell)  # Extract options using regex
            unique_options.update(options)

# Iterate through the DataFrame rows
for index, row in data.iterrows():
    for col in range(len(row)):
        # If the cell contains any of the unique options
        for option in unique_options:
            if isinstance(row[col], str) and option in row[col]:
                # Fill all cells to the left with the corresponding value
                for i in range(col - 1, -1, -1):
                    data.iloc[index, i] = row[col]
                break  # Break out of the loop once the option is found

In [53]:
data

,UNITED HEALTHCARE UNDERWRITING FULLY INSURED APPROVAL FORM - For Internal Use Only,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,FINAL SOLD RATES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AGE/SEX,NaN,2.16,NaN,NaN,NaN,NaN,NaN,NaN
2,ORIGINATING SITE,NaN,Rhode Island,NaN,NaN,NaN,EFFECTIVE DATE,1/1/2024,THROUGH,12/31/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,BENEFIT ALLY QUOTED,NaN,N
3,GROUP NAME,NaN,GREATER NOIDA MENTAL HEALTH CENTER,NaN,NaN,NaN,ACCOUNT EXECUTIVE,Bryan Cranston,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NEW BUSINESS/RENEWAL,NaN,NEW BUSINESS,NaN,NaN,NaN,UNDERWRITER,Kristen Bell,NaN,NaN,NaN,HP ALLIANCE GROUP:,NaN,No,NaN,NaN,NaN,SPECIALITY COMMISSION,NaN,0.1
5,CARRIER REPLACE Y/N:,NaN,Y,NaN,NaN,NaN,COMMISSION,$31.00 PEM,SERVICE FEE,NaN,NaN,# OF SITUS STATES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,MULTI-SITE Y/N:,NaN,Y,NaN,NaN,NaN,COMMISSION NOTES,NaN,NaN,NaN,NaN,SECOND SITUS STATE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,DATE,NaN,10/4/2023,NaN,NaN,NaN,AGGREGATED GRP #s,NaN,NaN,NaN,NaN,HP RATE TIER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,COMPOSITE RENEWAL ACTION,NaN,NaN,NaN,NaN,NaN,SUBJECT TO MED U/W,___ YES,___ NO,NaN,NaN,CASE CHARACTERISTIC SCORE,NaN,15,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,OPTION 1,OPTION 1,OPTION 1,OPTION 1,OPTION 1,OPTION 1,OPTION 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,NaN,NaN,NaN,NaN,NaN,NaN,Premium Incl.,Premium,NaN,NaN,NaN,NaN,NaN
12,Situs State,NH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Subs,Mbrs,"Comm, Fees",Less Fees,NaN,NaN,NaN,NaN,NaN
13,License (HMO vs Ins Co),EPO,NaN,NaN,Benefit Plan,NaN,CPIJ Mod,(Granite Advantage EPO OA),NaN,NaN,EE Only,87,NaN,$ 886.06,NaN,NaN,NaN,NaN,NaN,NaN
14,Sites(s)/Network(s),National- Excl. OOA,NaN,NaN,In Network Copays,NaN,"PCP $10/$10, SPC $25/$25, OP $250/D&C, IP D&C,...",NaN,NaN,NaN,EE + Spouse,25,NaN,$ 1064.07,NaN,NaN,NaN,NaN,NaN,NaN
15,Platform/Product,CiTrus,Gravel Advantage EPO,NaN,In Net Ded/Coins/OOP,NaN,"Ded $5,000/$10,000 (Emb), Coins 80%, OOP $6,00...",NaN,NaN,NaN,EE + Childern,38,NaN,$ 2035.58,NaN,NaN,NaN,NaN,NaN,NaN
16,Multiple Plan Offering:,Dual Option with 2,NaN,NaN,Out of Network,NaN,"Ded N/A, Coins N/A, OOP N/A",NaN,NaN,NaN,Family,37,NaN,$ 1037.07,NaN,NaN,NaN,NaN,NaN,NaN
17,Coverage for Retirees:,N,Min Value,Pass,Other/Riders,NaN,"UHCR Prem,",NaN,NaN,NaN,Totals/PMPM,170,47,$ 103.487,NaN,NaN,NaN,NaN,NaN,NaN
18,Legal Entity,THFIC,NaN,NaN,Drug Benefit,NaN,"$3/$33/$50, 2 MO (Adv PDL)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,Rating Group,NaN,Rx Plan: TH15-INT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,OPTION 2,OPTION 2,OPTION 2,OPTION 2,OPTION 2,OPTION 2,OPTION 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,NaN,NaN,NaN,NaN,NaN,NaN,Premium Incl.,Premium,NaN,NaN,NaN,NaN,NaN
24,Situs State,NH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Subs,Mbrs,"Comm, Fees",Less Fees,NaN,NaN,NaN,NaN,NaN
25,License (HMO vs Ins Co),EPO,NaN,NaN,Benefit Plan,NaN,CPIJ Mod,(Granite Advantage EPO OA),NaN,NaN,EE Only,87,NaN,$ 886.06,NaN,NaN,NaN,NaN,NaN,NaN
26,Sites(s)/Network(s),National- Excl. OOA,NaN,NaN,In Network Copays,NaN,"PCP $20/$20, SPC $35/$35, OP $350/D&C, IP D&C,...",NaN,NaN,NaN,EE + Spouse,25,NaN,$ 1064.07,NaN,NaN,NaN,NaN,NaN,NaN
27,Platform/Product,CiTrus,Gravel Advantage EPO Saver,NaN,In Net Ded/Coins/OOP,NaN,"Ded $6,000/$12,000 (Emb), Coins 90%, OOP $7,00...",NaN,NaN,NaN,EE + Childern,38,NaN,$ 2035.58,NaN,NaN,NaN,NaN,NaN,NaN
28,Multiple Plan Offering:,Dual Option with 2,NaN,NaN,Out of Network,NaN,"Ded N/A, Coins N/A, OOP N/A",NaN,NaN,NaN,Family,37,NaN,$ 1037.07,NaN,NaN,NaN,NaN,NaN,NaN
29,Coverage for Retirees:,N,Min Value,Pass,Other/Riders,NaN,"UHCR Prem,",NaN,NaN,NaN,Totals/PMPM,170,47,$ 103.487,NaN,NaN,NaN,NaN,NaN,NaN
30,Legal Entity,THFIC,NaN,NaN,Drug Benefit,NaN,"$4/$44/$60, 2 MO (Adv PDL)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,Rating Group,NaN,Rx Plan: TH15-INT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,GRAND TOTAL,NaN,NaN,NaN,NaN,NaN,NaN,Premium Incl.,Premium,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Subs,Mbrs,"Comm, Fees",Less Fees,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EE Only,87,NaN,$ 886.06,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EE + Spouse,25,NaN,$ 1064.07,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EE + Childern,38,NaN,$ 2035.58,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Family,37,NaN,$ 1037.07,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Totals/PMPM,170,47,$ 103.487,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,WER HGFDD dfghjl hbvc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,"# Extracting the words ""PCP"", ""SPC"", ""UC"", ""ER...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,"filtered_df.insert(loc=1, column='Type', value...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,"# Fill NaN values in the ""Type"" column with a ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,"filtered_df['Type'].fillna('', inplace=True)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,# Display the modified DataFrame,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,print(filtered_df),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
# Keeping only columns Unnamed: 4 to Unnamed: 7
# Keeping only columns Unnamed: 4 to Unnamed: 7
df = data.iloc[:, 4:8]

# Displaying the modified dataframe
df

,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,NaN,NaN,EFFECTIVE DATE,1/1/2024
3,NaN,NaN,ACCOUNT EXECUTIVE,Bryan Cranston
4,NaN,NaN,UNDERWRITER,Kristen Bell
5,NaN,NaN,COMMISSION,$31.00 PEM
6,NaN,NaN,COMMISSION NOTES,NaN
7,NaN,NaN,AGGREGATED GRP #s,NaN
8,NaN,NaN,SUBJECT TO MED U/W,___ YES
9,NaN,NaN,NaN,NaN
10,OPTION 1,OPTION 1,OPTION 1,NaN
11,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,NaN
12,NaN,NaN,NaN,NaN
13,Benefit Plan,NaN,CPIJ Mod,(Granite Advantage EPO OA)
14,In Network Copays,NaN,"PCP $10/$10, SPC $25/$25, OP $250/D&C, IP D&C,...",NaN
15,In Net Ded/Coins/OOP,NaN,"Ded $5,000/$10,000 (Emb), Coins 80%, OOP $6,00...",NaN
16,Out of Network,NaN,"Ded N/A, Coins N/A, OOP N/A",NaN
17,Other/Riders,NaN,"UHCR Prem,",NaN
18,Drug Benefit,NaN,"$3/$33/$50, 2 MO (Adv PDL)",NaN
19,Rating Group,NaN,Rx Plan: TH15-INT,NaN
20,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN
22,OPTION 2,OPTION 2,OPTION 2,NaN
23,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,NaN
24,NaN,NaN,NaN,NaN
25,Benefit Plan,NaN,CPIJ Mod,(Granite Advantage EPO OA)
26,In Network Copays,NaN,"PCP $20/$20, SPC $35/$35, OP $350/D&C, IP D&C,...",NaN
27,In Net Ded/Coins/OOP,NaN,"Ded $6,000/$12,000 (Emb), Coins 90%, OOP $7,00...",NaN
28,Out of Network,NaN,"Ded N/A, Coins N/A, OOP N/A",NaN
29,Other/Riders,NaN,"UHCR Prem,",NaN
30,Drug Benefit,NaN,"$4/$44/$60, 2 MO (Adv PDL)",NaN
31,Rating Group,NaN,Rx Plan: TH15-INT,NaN
32,NaN,NaN,NaN,NaN
33,NaN,NaN,GRAND TOTAL,NaN
34,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN

In [55]:
import numpy as np 

# Define a function to shift non-NaN values to the left
def shift_non_nan(row):
    shifted_row = [np.nan] * len(row)
    last_non_nan_index = None
    for i, value in enumerate(row):
        if pd.notnull(value):
            if last_non_nan_index is None:
                shifted_row[0] = value
                last_non_nan_index = 0
            else:
                last_non_nan_index += 1
                shifted_row[last_non_nan_index] = value
    return pd.Series(shifted_row)

# Apply the function to each row of the dataframe
df = df.apply(shift_non_nan, axis=1)

# Display the modified dataframe
df

,0,1,2,3
0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,EFFECTIVE DATE,1/1/2024,NaN,NaN
3,ACCOUNT EXECUTIVE,Bryan Cranston,NaN,NaN
4,UNDERWRITER,Kristen Bell,NaN,NaN
5,COMMISSION,$31.00 PEM,NaN,NaN
6,COMMISSION NOTES,NaN,NaN,NaN
7,AGGREGATED GRP #s,NaN,NaN,NaN
8,SUBJECT TO MED U/W,___ YES,NaN,NaN
9,NaN,NaN,NaN,NaN
10,OPTION 1,OPTION 1,OPTION 1,NaN
11,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,NaN
12,NaN,NaN,NaN,NaN
13,Benefit Plan,CPIJ Mod,(Granite Advantage EPO OA),NaN
14,In Network Copays,"PCP $10/$10, SPC $25/$25, OP $250/D&C, IP D&C,...",NaN,NaN
15,In Net Ded/Coins/OOP,"Ded $5,000/$10,000 (Emb), Coins 80%, OOP $6,00...",NaN,NaN
16,Out of Network,"Ded N/A, Coins N/A, OOP N/A",NaN,NaN
17,Other/Riders,"UHCR Prem,",NaN,NaN
18,Drug Benefit,"$3/$33/$50, 2 MO (Adv PDL)",NaN,NaN
19,Rating Group,Rx Plan: TH15-INT,NaN,NaN
20,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN
22,OPTION 2,OPTION 2,OPTION 2,NaN
23,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,NaN
24,NaN,NaN,NaN,NaN
25,Benefit Plan,CPIJ Mod,(Granite Advantage EPO OA),NaN
26,In Network Copays,"PCP $20/$20, SPC $35/$35, OP $350/D&C, IP D&C,...",NaN,NaN
27,In Net Ded/Coins/OOP,"Ded $6,000/$12,000 (Emb), Coins 90%, OOP $7,00...",NaN,NaN
28,Out of Network,"Ded N/A, Coins N/A, OOP N/A",NaN,NaN
29,Other/Riders,"UHCR Prem,",NaN,NaN
30,Drug Benefit,"$4/$44/$60, 2 MO (Adv PDL)",NaN,NaN
31,Rating Group,Rx Plan: TH15-INT,NaN,NaN
32,NaN,NaN,NaN,NaN
33,GRAND TOTAL,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN

In [56]:
import pandas as pd

# Assuming your DataFrame is named df

# Find the rows where 'Benefit Plan' is mentioned
benefit_plan_rows = df[df.apply(lambda row: 'Benefit Plan' in row.values, axis=1)]

# Merge cells to the right of 'Benefit Plan' rows
for index, row in benefit_plan_rows.iterrows():
    # Find the index of the column where 'Benefit Plan' is located
    benefit_plan_index = np.where(row == 'Benefit Plan')[0][0]
    # Find non-NaN values to merge
    non_nan_values = row.iloc[benefit_plan_index + 1:].dropna().tolist()
    # Merge non-NaN values into a single cell
    merged_value = ' '.join(str(cell) for cell in non_nan_values)
    # Assign the merged value to the cell next to 'Benefit Plan'
    df.at[index, benefit_plan_index + 1] = merged_value
df

,0,1,2,3
0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,EFFECTIVE DATE,1/1/2024,NaN,NaN
3,ACCOUNT EXECUTIVE,Bryan Cranston,NaN,NaN
4,UNDERWRITER,Kristen Bell,NaN,NaN
5,COMMISSION,$31.00 PEM,NaN,NaN
6,COMMISSION NOTES,NaN,NaN,NaN
7,AGGREGATED GRP #s,NaN,NaN,NaN
8,SUBJECT TO MED U/W,___ YES,NaN,NaN
9,NaN,NaN,NaN,NaN
10,OPTION 1,OPTION 1,OPTION 1,NaN
11,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,NaN
12,NaN,NaN,NaN,NaN
13,Benefit Plan,CPIJ Mod (Granite Advantage EPO OA),(Granite Advantage EPO OA),NaN
14,In Network Copays,"PCP $10/$10, SPC $25/$25, OP $250/D&C, IP D&C,...",NaN,NaN
15,In Net Ded/Coins/OOP,"Ded $5,000/$10,000 (Emb), Coins 80%, OOP $6,00...",NaN,NaN
16,Out of Network,"Ded N/A, Coins N/A, OOP N/A",NaN,NaN
17,Other/Riders,"UHCR Prem,",NaN,NaN
18,Drug Benefit,"$3/$33/$50, 2 MO (Adv PDL)",NaN,NaN
19,Rating Group,Rx Plan: TH15-INT,NaN,NaN
20,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN
22,OPTION 2,OPTION 2,OPTION 2,NaN
23,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,PRIMARY/SOLD PLAN,NaN
24,NaN,NaN,NaN,NaN
25,Benefit Plan,CPIJ Mod (Granite Advantage EPO OA),(Granite Advantage EPO OA),NaN
26,In Network Copays,"PCP $20/$20, SPC $35/$35, OP $350/D&C, IP D&C,...",NaN,NaN
27,In Net Ded/Coins/OOP,"Ded $6,000/$12,000 (Emb), Coins 90%, OOP $7,00...",NaN,NaN
28,Out of Network,"Ded N/A, Coins N/A, OOP N/A",NaN,NaN
29,Other/Riders,"UHCR Prem,",NaN,NaN
30,Drug Benefit,"$4/$44/$60, 2 MO (Adv PDL)",NaN,NaN
31,Rating Group,Rx Plan: TH15-INT,NaN,NaN
32,NaN,NaN,NaN,NaN
33,GRAND TOTAL,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN
46,NaN,NaN,NaN,NaN
47,NaN,NaN,NaN,NaN
48,NaN,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN
50,NaN,NaN,NaN,NaN

In [57]:
# Assuming your DataFrame is named df
df = df.drop(columns=[2, 3])
df

                       0                                                  1
0                    NaN                                                NaN
1                    NaN                                                NaN
2         EFFECTIVE DATE                                           1/1/2024
3      ACCOUNT EXECUTIVE                                     Bryan Cranston
4           UNDERWRITER                                        Kristen Bell
5             COMMISSION                                         $31.00 PEM
6       COMMISSION NOTES                                                NaN
7      AGGREGATED GRP #s                                                NaN
8     SUBJECT TO MED U/W                                            ___ YES
9                    NaN                                                NaN
10              OPTION 1                                           OPTION 1
11     PRIMARY/SOLD PLAN                                  PRIMARY/SOLD PLAN
12                   NaN                                                NaN
13          Benefit Plan                CPIJ Mod (Granite Advantage EPO OA)
14     In Network Copays  PCP $10/$10, SPC $25/$25, OP $250/D&C, IP D&C,...
15  In Net Ded/Coins/OOP  Ded $5,000/$10,000 (Emb), Coins 80%, OOP $6,00...
16        Out of Network                        Ded N/A, Coins N/A, OOP N/A
17          Other/Riders                                         UHCR Prem,
18          Drug Benefit                         $3/$33/$50, 2 MO (Adv PDL)
19          Rating Group                                  Rx Plan: TH15-INT
20                   NaN                                                NaN
21                   NaN                                                NaN
22              OPTION 2                                           OPTION 2
23     PRIMARY/SOLD PLAN                                  PRIMARY/SOLD PLAN
24                   NaN                                                NaN
25          Benefit Plan                CPIJ Mod (Granite Advantage EPO OA)
26     In Network Copays  PCP $20/$20, SPC $35/$35, OP $350/D&C, IP D&C,...
27  In Net Ded/Coins/OOP  Ded $6,000/$12,000 (Emb), Coins 90%, OOP $7,00...
28        Out of Network                        Ded N/A, Coins N/A, OOP N/A
29          Other/Riders                                         UHCR Prem,
30          Drug Benefit                         $4/$44/$60, 2 MO (Adv PDL)
31          Rating Group                                  Rx Plan: TH15-INT
32                   NaN                                                NaN
33           GRAND TOTAL                                                NaN
34                   NaN                                                NaN
35                   NaN                                                NaN
36                   NaN                                                NaN
37                   NaN                                                NaN
38                   NaN                                                NaN
39                   NaN                                                NaN
40                   NaN                                                NaN
41                   NaN                                                NaN
42                   NaN                                                NaN
43                   NaN                                                NaN
44                   NaN                                                NaN
45                   NaN                                                NaN
46                   NaN                                                NaN
47                   NaN                                                NaN
48                   NaN                                                NaN
49                   NaN                                                NaN
50                   NaN                                                NaN

In [58]:
df = df.dropna()
df

                       0                                                  1
2         EFFECTIVE DATE                                           1/1/2024
3      ACCOUNT EXECUTIVE                                     Bryan Cranston
4           UNDERWRITER                                        Kristen Bell
5             COMMISSION                                         $31.00 PEM
8     SUBJECT TO MED U/W                                            ___ YES
10              OPTION 1                                           OPTION 1
11     PRIMARY/SOLD PLAN                                  PRIMARY/SOLD PLAN
13          Benefit Plan                CPIJ Mod (Granite Advantage EPO OA)
14     In Network Copays  PCP $10/$10, SPC $25/$25, OP $250/D&C, IP D&C,...
15  In Net Ded/Coins/OOP  Ded $5,000/$10,000 (Emb), Coins 80%, OOP $6,00...
16        Out of Network                        Ded N/A, Coins N/A, OOP N/A
17          Other/Riders                                         UHCR Prem,
18          Drug Benefit                         $3/$33/$50, 2 MO (Adv PDL)
19          Rating Group                                  Rx Plan: TH15-INT
22              OPTION 2                                           OPTION 2
23     PRIMARY/SOLD PLAN                                  PRIMARY/SOLD PLAN
25          Benefit Plan                CPIJ Mod (Granite Advantage EPO OA)
26     In Network Copays  PCP $20/$20, SPC $35/$35, OP $350/D&C, IP D&C,...
27  In Net Ded/Coins/OOP  Ded $6,000/$12,000 (Emb), Coins 90%, OOP $7,00...
28        Out of Network                        Ded N/A, Coins N/A, OOP N/A
29          Other/Riders                                         UHCR Prem,
30          Drug Benefit                         $4/$44/$60, 2 MO (Adv PDL)
31          Rating Group                                  Rx Plan: TH15-INT

In [59]:
import pandas as pd

import pandas as pd

# Assuming you have a DataFrame called df with appropriate columns

# Function to split cells containing commas into separate rows for applicable columns
def split_rows(df):
    new_rows = []
    for index, row in df.iterrows():
        split_row = False  # Flag to check if splitting occurred for this row
        for column_name, cell_value in row.items():
            if ',' in str(cell_value):
                split_row = True  # Set flag to True if splitting occurred for any column
                details = str(cell_value).split(', ')
                for detail in details:
                    new_row = row.copy()  # Copy the original row
                    new_row[column_name] = detail.strip()  # Update the cell value
                    new_rows.append(new_row)  # Append the new row to the list
                break  # Break out of the loop once splitting occurs for any column
        if not split_row:
            new_rows.append(row)  # Append the original row if no splitting occurred
    new_df = pd.DataFrame(new_rows)  # Creating a new DataFrame with split rows
    return new_df

# Call the function with the DataFrame
new_df = split_rows(df)

# Display the new DataFrame
new_df

                       0                                    1
2         EFFECTIVE DATE                             1/1/2024
3      ACCOUNT EXECUTIVE                       Bryan Cranston
4           UNDERWRITER                          Kristen Bell
5             COMMISSION                           $31.00 PEM
8     SUBJECT TO MED U/W                              ___ YES
10              OPTION 1                             OPTION 1
11     PRIMARY/SOLD PLAN                    PRIMARY/SOLD PLAN
13          Benefit Plan  CPIJ Mod (Granite Advantage EPO OA)
14     In Network Copays                          PCP $10/$10
14     In Network Copays                          SPC $25/$25
14     In Network Copays                          OP $250/D&C
14     In Network Copays                               IP D&C
14     In Network Copays                                UC$10
14     In Network Copays                               ER$230
14     In Network Copays                          MD $230/D&C
14     In Network Copays                         X-Ray $0/D&C
14     In Network Copays                           Lab $0/D&C
15  In Net Ded/Coins/OOP             Ded $5,000/$10,000 (Emb)
15  In Net Ded/Coins/OOP                            Coins 80%
15  In Net Ded/Coins/OOP                   OOP $6,000/$12,000
16        Out of Network                              Ded N/A
16        Out of Network                            Coins N/A
16        Out of Network                              OOP N/A
17          Other/Riders                           UHCR Prem,
18          Drug Benefit                           $3/$33/$50
18          Drug Benefit                       2 MO (Adv PDL)
19          Rating Group                    Rx Plan: TH15-INT
22              OPTION 2                             OPTION 2
23     PRIMARY/SOLD PLAN                    PRIMARY/SOLD PLAN
25          Benefit Plan  CPIJ Mod (Granite Advantage EPO OA)
26     In Network Copays                          PCP $20/$20
26     In Network Copays                          SPC $35/$35
26     In Network Copays                          OP $350/D&C
26     In Network Copays                               IP D&C
26     In Network Copays                                UC$20
26     In Network Copays                               ER$330
26     In Network Copays                          MD $330/D&C
26     In Network Copays                         X-Ray $0/D&C
26     In Network Copays                           Lab $0/D&C
27  In Net Ded/Coins/OOP             Ded $6,000/$12,000 (Emb)
27  In Net Ded/Coins/OOP                            Coins 90%
27  In Net Ded/Coins/OOP                   OOP $7,000/$12,000
28        Out of Network                              Ded N/A
28        Out of Network                            Coins N/A
28        Out of Network                              OOP N/A
29          Other/Riders                           UHCR Prem,
30          Drug Benefit                           $4/$44/$60
30          Drug Benefit                       2 MO (Adv PDL)
31          Rating Group                    Rx Plan: TH15-INT

In [60]:
# Assign unique indices
new_df.index = range(len(new_df))

new_df

                       0                                    1
0         EFFECTIVE DATE                             1/1/2024
1      ACCOUNT EXECUTIVE                       Bryan Cranston
2           UNDERWRITER                          Kristen Bell
3             COMMISSION                           $31.00 PEM
4     SUBJECT TO MED U/W                              ___ YES
5               OPTION 1                             OPTION 1
6      PRIMARY/SOLD PLAN                    PRIMARY/SOLD PLAN
7           Benefit Plan  CPIJ Mod (Granite Advantage EPO OA)
8      In Network Copays                          PCP $10/$10
9      In Network Copays                          SPC $25/$25
10     In Network Copays                          OP $250/D&C
11     In Network Copays                               IP D&C
12     In Network Copays                                UC$10
13     In Network Copays                               ER$230
14     In Network Copays                          MD $230/D&C
15     In Network Copays                         X-Ray $0/D&C
16     In Network Copays                           Lab $0/D&C
17  In Net Ded/Coins/OOP             Ded $5,000/$10,000 (Emb)
18  In Net Ded/Coins/OOP                            Coins 80%
19  In Net Ded/Coins/OOP                   OOP $6,000/$12,000
20        Out of Network                              Ded N/A
21        Out of Network                            Coins N/A
22        Out of Network                              OOP N/A
23          Other/Riders                           UHCR Prem,
24          Drug Benefit                           $3/$33/$50
25          Drug Benefit                       2 MO (Adv PDL)
26          Rating Group                    Rx Plan: TH15-INT
27              OPTION 2                             OPTION 2
28     PRIMARY/SOLD PLAN                    PRIMARY/SOLD PLAN
29          Benefit Plan  CPIJ Mod (Granite Advantage EPO OA)
30     In Network Copays                          PCP $20/$20
31     In Network Copays                          SPC $35/$35
32     In Network Copays                          OP $350/D&C
33     In Network Copays                               IP D&C
34     In Network Copays                                UC$20
35     In Network Copays                               ER$330
36     In Network Copays                          MD $330/D&C
37     In Network Copays                         X-Ray $0/D&C
38     In Network Copays                           Lab $0/D&C
39  In Net Ded/Coins/OOP             Ded $6,000/$12,000 (Emb)
40  In Net Ded/Coins/OOP                            Coins 90%
41  In Net Ded/Coins/OOP                   OOP $7,000/$12,000
42        Out of Network                              Ded N/A
43        Out of Network                            Coins N/A
44        Out of Network                              OOP N/A
45          Other/Riders                           UHCR Prem,
46          Drug Benefit                           $4/$44/$60
47          Drug Benefit                       2 MO (Adv PDL)
48          Rating Group                    Rx Plan: TH15-INT

In [61]:
# Words to check for deletion
words_to_delete = ['OP', 'IP', 'MD', 'X-Ray', 'Lab', 'Riders', 'Drug Benefit', 'Rating Group']

import re

# Function to filter out rows containing specified words
def filter_rows(df, words_to_delete):
    indices_to_drop = []  # List to store indices of rows to drop
    # Iterate through each row
    for index, row in df.iterrows():
        # Flag to check if any word to delete is found
        delete_row = False
        # Iterate through each cell value in the row
        for cell_value in row.values:
            # Check if any word to delete is present in the cell value
            for word in words_to_delete:
                if re.search(r'\b' + word + r'\b', str(cell_value)):
                    # If any word is found, set delete_row flag to True
                    delete_row = True
                    break  # No need to continue checking for words in this row
            if delete_row:
                break  # No need to check further if any word is found in this row
        if delete_row:
            indices_to_drop.append(index)  # Store the index of the row to drop
    # Drop the rows outside of the loop to avoid modifying DataFrame while iterating
    df_filtered = df.drop(indices_to_drop)
    return df_filtered

# Call the function with the DataFrame
filtered_df = filter_rows(new_df, words_to_delete)
# Display the filtered DataFrame
filtered_df

                       0                                    1
0         EFFECTIVE DATE                             1/1/2024
1      ACCOUNT EXECUTIVE                       Bryan Cranston
2           UNDERWRITER                          Kristen Bell
3             COMMISSION                           $31.00 PEM
4     SUBJECT TO MED U/W                              ___ YES
5               OPTION 1                             OPTION 1
6      PRIMARY/SOLD PLAN                    PRIMARY/SOLD PLAN
7           Benefit Plan  CPIJ Mod (Granite Advantage EPO OA)
8      In Network Copays                          PCP $10/$10
9      In Network Copays                          SPC $25/$25
12     In Network Copays                                UC$10
13     In Network Copays                               ER$230
17  In Net Ded/Coins/OOP             Ded $5,000/$10,000 (Emb)
18  In Net Ded/Coins/OOP                            Coins 80%
19  In Net Ded/Coins/OOP                   OOP $6,000/$12,000
20        Out of Network                              Ded N/A
21        Out of Network                            Coins N/A
22        Out of Network                              OOP N/A
27              OPTION 2                             OPTION 2
28     PRIMARY/SOLD PLAN                    PRIMARY/SOLD PLAN
29          Benefit Plan  CPIJ Mod (Granite Advantage EPO OA)
30     In Network Copays                          PCP $20/$20
31     In Network Copays                          SPC $35/$35
34     In Network Copays                                UC$20
35     In Network Copays                               ER$330
39  In Net Ded/Coins/OOP             Ded $6,000/$12,000 (Emb)
40  In Net Ded/Coins/OOP                            Coins 90%
41  In Net Ded/Coins/OOP                   OOP $7,000/$12,000
42        Out of Network                              Ded N/A
43        Out of Network                            Coins N/A
44        Out of Network                              OOP N/A

In [62]:
# Add a space before each $ sign in the DataFrame
filtered_df = filtered_df.applymap(lambda x: str(x).replace('$', ' $') if isinstance(x, str) else x)

# Display the modified DataFrame
filtered_df

                       0                                    1
0         EFFECTIVE DATE                             1/1/2024
1      ACCOUNT EXECUTIVE                       Bryan Cranston
2           UNDERWRITER                          Kristen Bell
3             COMMISSION                           $31.00 PEM
4     SUBJECT TO MED U/W                              ___ YES
5               OPTION 1                             OPTION 1
6      PRIMARY/SOLD PLAN                    PRIMARY/SOLD PLAN
7           Benefit Plan  CPIJ Mod (Granite Advantage EPO OA)
8      In Network Copays                        PCP  $10/ $10
9      In Network Copays                        SPC  $25/ $25
12     In Network Copays                               UC $10
13     In Network Copays                              ER $230
17  In Net Ded/Coins/OOP           Ded  $5,000/ $10,000 (Emb)
18  In Net Ded/Coins/OOP                            Coins 80%
19  In Net Ded/Coins/OOP                 OOP  $6,000/ $12,000
20        Out of Network                              Ded N/A
21        Out of Network                            Coins N/A
22        Out of Network                              OOP N/A
27              OPTION 2                             OPTION 2
28     PRIMARY/SOLD PLAN                    PRIMARY/SOLD PLAN
29          Benefit Plan  CPIJ Mod (Granite Advantage EPO OA)
30     In Network Copays                        PCP  $20/ $20
31     In Network Copays                        SPC  $35/ $35
34     In Network Copays                               UC $20
35     In Network Copays                              ER $330
39  In Net Ded/Coins/OOP           Ded  $6,000/ $12,000 (Emb)
40  In Net Ded/Coins/OOP                            Coins 90%
41  In Net Ded/Coins/OOP                 OOP  $7,000/ $12,000
42        Out of Network                              Ded N/A
43        Out of Network                            Coins N/A
44        Out of Network                              OOP N/A

In [63]:
# Extracting the words "PCP", "SPC", "UC", "ER", "Ded", and "Coins" into a separate column
filtered_df.insert(loc=1, column='Type', value=filtered_df[1].str.extract(r'(PCP|SPC|UC|ER|Ded|Coins|OOP)', expand=False))

# Fill NaN values in the "Type" column with a default value
filtered_df['Type'].fillna('', inplace=True)

# Display the modified DataFrame
filtered_df

                       0   Type                                    1
0         EFFECTIVE DATE                                    1/1/2024
1      ACCOUNT EXECUTIVE                              Bryan Cranston
2           UNDERWRITER                                 Kristen Bell
3             COMMISSION                                  $31.00 PEM
4     SUBJECT TO MED U/W                                     ___ YES
5               OPTION 1                                    OPTION 1
6      PRIMARY/SOLD PLAN                           PRIMARY/SOLD PLAN
7           Benefit Plan         CPIJ Mod (Granite Advantage EPO OA)
8      In Network Copays    PCP                        PCP  $10/ $10
9      In Network Copays    SPC                        SPC  $25/ $25
12     In Network Copays     UC                               UC $10
13     In Network Copays     ER                              ER $230
17  In Net Ded/Coins/OOP    Ded           Ded  $5,000/ $10,000 (Emb)
18  In Net Ded/Coins/OOP  Coins                            Coins 80%
19  In Net Ded/Coins/OOP    OOP                 OOP  $6,000/ $12,000
20        Out of Network    Ded                              Ded N/A
21        Out of Network  Coins                            Coins N/A
22        Out of Network    OOP                              OOP N/A
27              OPTION 2                                    OPTION 2
28     PRIMARY/SOLD PLAN                           PRIMARY/SOLD PLAN
29          Benefit Plan         CPIJ Mod (Granite Advantage EPO OA)
30     In Network Copays    PCP                        PCP  $20/ $20
31     In Network Copays    SPC                        SPC  $35/ $35
34     In Network Copays     UC                               UC $20
35     In Network Copays     ER                              ER $330
39  In Net Ded/Coins/OOP    Ded           Ded  $6,000/ $12,000 (Emb)
40  In Net Ded/Coins/OOP  Coins                            Coins 90%
41  In Net Ded/Coins/OOP    OOP                 OOP  $7,000/ $12,000
42        Out of Network    Ded                              Ded N/A
43        Out of Network  Coins                            Coins N/A
44        Out of Network    OOP                              OOP N/A

In [64]:
# Remove the words "PCP", "SPC", "UC", "ER", "Ded", and "Coins" from the actual column
filtered_df[1] = filtered_df[1].str.replace(r'(PCP|SPC|UC|ER|Ded|Coins|OOP)', '', regex=True)

# Display the modified DataFrame
filtered_df

                       0   Type                                    1
0         EFFECTIVE DATE                                    1/1/2024
1      ACCOUNT EXECUTIVE                              Bryan Cranston
2           UNDERWRITER                                 Kristen Bell
3             COMMISSION                                  $31.00 PEM
4     SUBJECT TO MED U/W                                     ___ YES
5               OPTION 1                                    OPTION 1
6      PRIMARY/SOLD PLAN                           PRIMARY/SOLD PLAN
7           Benefit Plan         CPIJ Mod (Granite Advantage EPO OA)
8      In Network Copays    PCP                             $10/ $10
9      In Network Copays    SPC                             $25/ $25
12     In Network Copays     UC                                  $10
13     In Network Copays     ER                                 $230
17  In Net Ded/Coins/OOP    Ded                $5,000/ $10,000 (Emb)
18  In Net Ded/Coins/OOP  Coins                                  80%
19  In Net Ded/Coins/OOP    OOP                      $6,000/ $12,000
20        Out of Network    Ded                                  N/A
21        Out of Network  Coins                                  N/A
22        Out of Network    OOP                                  N/A
27              OPTION 2                                    OPTION 2
28     PRIMARY/SOLD PLAN                           PRIMARY/SOLD PLAN
29          Benefit Plan         CPIJ Mod (Granite Advantage EPO OA)
30     In Network Copays    PCP                             $20/ $20
31     In Network Copays    SPC                             $35/ $35
34     In Network Copays     UC                                  $20
35     In Network Copays     ER                                 $330
39  In Net Ded/Coins/OOP    Ded                $6,000/ $12,000 (Emb)
40  In Net Ded/Coins/OOP  Coins                                  90%
41  In Net Ded/Coins/OOP    OOP                      $7,000/ $12,000
42        Out of Network    Ded                                  N/A
43        Out of Network  Coins                                  N/A
44        Out of Network    OOP                                  N/A

In [65]:
# Merge the first and second columns
filtered_df.insert(loc=0, column='Merged', value=filtered_df[0].astype(str) + " " + filtered_df['Type'].astype(str))

# Drop the 'Type' and the original first column
filtered_df.drop(columns=[0, 'Type'], inplace=True)

# Display the modified DataFrame
filtered_df

                        Merged                                    1
0              EFFECTIVE DATE                              1/1/2024
1           ACCOUNT EXECUTIVE                        Bryan Cranston
2                UNDERWRITER                           Kristen Bell
3                  COMMISSION                            $31.00 PEM
4          SUBJECT TO MED U/W                               ___ YES
5                    OPTION 1                              OPTION 1
6           PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
7                Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
8        In Network Copays PCP                             $10/ $10
9        In Network Copays SPC                             $25/ $25
12        In Network Copays UC                                  $10
13        In Network Copays ER                                 $230
17    In Net Ded/Coins/OOP Ded                $5,000/ $10,000 (Emb)
18  In Net Ded/Coins/OOP Coins                                  80%
19    In Net Ded/Coins/OOP OOP                      $6,000/ $12,000
20          Out of Network Ded                                  N/A
21        Out of Network Coins                                  N/A
22          Out of Network OOP                                  N/A
27                   OPTION 2                              OPTION 2
28          PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
29               Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
30       In Network Copays PCP                             $20/ $20
31       In Network Copays SPC                             $35/ $35
34        In Network Copays UC                                  $20
35        In Network Copays ER                                 $330
39    In Net Ded/Coins/OOP Ded                $6,000/ $12,000 (Emb)
40  In Net Ded/Coins/OOP Coins                                  90%
41    In Net Ded/Coins/OOP OOP                      $7,000/ $12,000
42          Out of Network Ded                                  N/A
43        Out of Network Coins                                  N/A
44          Out of Network OOP                                  N/A

In [66]:
# Set column names to empty strings
filtered_df.columns = [''] * len(filtered_df.columns)

# Reset index
filtered_df.reset_index(drop=True, inplace=True)

# Display the modified DataFrame without column and index headers
filtered_df

0              EFFECTIVE DATE                              1/1/2024
1           ACCOUNT EXECUTIVE                        Bryan Cranston
2                UNDERWRITER                           Kristen Bell
3                  COMMISSION                            $31.00 PEM
4          SUBJECT TO MED U/W                               ___ YES
5                    OPTION 1                              OPTION 1
6           PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
7                Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
8        In Network Copays PCP                             $10/ $10
9        In Network Copays SPC                             $25/ $25
10        In Network Copays UC                                  $10
11        In Network Copays ER                                 $230
12    In Net Ded/Coins/OOP Ded                $5,000/ $10,000 (Emb)
13  In Net Ded/Coins/OOP Coins                                  80%
14    In Net Ded/Coins/OOP OOP                      $6,000/ $12,000
15          Out of Network Ded                                  N/A
16        Out of Network Coins                                  N/A
17          Out of Network OOP                                  N/A
18                   OPTION 2                              OPTION 2
19          PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
20               Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
21       In Network Copays PCP                             $20/ $20
22       In Network Copays SPC                             $35/ $35
23        In Network Copays UC                                  $20
24        In Network Copays ER                                 $330
25    In Net Ded/Coins/OOP Ded                $6,000/ $12,000 (Emb)
26  In Net Ded/Coins/OOP Coins                                  90%
27    In Net Ded/Coins/OOP OOP                      $7,000/ $12,000
28          Out of Network Ded                                  N/A
29        Out of Network Coins                                  N/A
30          Out of Network OOP                                  N/A

In [67]:
import pandas as pd
import numpy as np

def process_filtered_df(filtered_df):
    # Assuming filtered_df is your DataFrame

    # Get the value of the first row in the first column
    first_cell_value = filtered_df.iloc[0, 0]

    # Find the index of "MNS"
    index_of_MNS = first_cell_value.find("MNS")

    # Split the string into two parts based on the index of "MNS"
    before_MNS = first_cell_value[:index_of_MNS]
    including_after_MNS = first_cell_value[index_of_MNS:]

    # Create two new rows with split values
    new_row_before = filtered_df.iloc[0].copy()
    new_row_before[0] = before_MNS

    new_row_after = filtered_df.iloc[0].copy()
    new_row_after[0] = including_after_MNS

    # Insert new rows into the DataFrame
    filtered_df.loc[1] = pd.Series(new_row_before)
    filtered_df.loc[2] = pd.Series(new_row_after)

    # Drop the original row
    filtered_df.drop(0, inplace=True)

    # Reset index
    filtered_df.reset_index(drop=True, inplace=True)

    # Swap values: 1st row in the 1st column with 1st row in the 2nd column
    temp = filtered_df.iloc[0, 0]
    filtered_df.iloc[0, 0] = filtered_df.iloc[0, 1]
    filtered_df.iloc[0, 1] = temp

    # Swap values: 2nd row in the 1st column with 2nd row in the 2nd column
    temp = filtered_df.iloc[1, 0]
    filtered_df.iloc[1, 0] = filtered_df.iloc[1, 1]
    filtered_df.iloc[1, 1] = temp

    # Fill the first NaN value in the first column with 'Group Name'
    filtered_df.iloc[:, 0] = filtered_df.iloc[:, 0].fillna('Group Name', limit=1)

    # Fill the second NaN value in the first column with 'MNS ID'
    filtered_df.iloc[:, 0] = filtered_df.iloc[:, 0].fillna('MNS ID', limit=1)

    return filtered_df

# Example usage:
#filtered_df = ...  # Your existing DataFrame
processed_df = process_filtered_df(filtered_df)
print(processed_df)

0                     1/1/2024                       EFFECTIVE DATE
1                     1/1/2024
2                  COMMISSION                            $31.00 PEM
3          SUBJECT TO MED U/W                               ___ YES
4                    OPTION 1                              OPTION 1
5           PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
6                Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
7        In Network Copays PCP                             $10/ $10
8        In Network Copays SPC                             $25/ $25
9         In Network Copays UC                                  $10
10        In Network Copays ER                                 $230
11    In Net Ded/Coins/OOP Ded                $5,000/ $10,000 (Emb)
12  In Net Ded/Coins/OOP Coins                                  80%
13    In Net Ded/Coins/OOP OOP                      $6,000/ $12,000
14          Out of Network Ded                                  N/A
15        Out of Network Coins                                  N/A
16          Out of Network OOP                                  N/A
17                   OPTION 2                              OPTION 2
18          PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
19               Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
20       In Network Copays PCP                             $20/ $20
21       In Network Copays SPC                             $35/ $35
22        In Network Copays UC                                  $20
23        In Network Copays ER                                 $330
24    In Net Ded/Coins/OOP Ded                $6,000/ $12,000 (Emb)
25  In Net Ded/Coins/OOP Coins                                  90%
26    In Net Ded/Coins/OOP OOP                      $7,000/ $12,000
27          Out of Network Ded                                  N/A
28        Out of Network Coins                                  N/A
29          Out of Network OOP                                  N/A

In [68]:
import pandas as pd

# Read the Excel file and extract the sheet name
xls = pd.ExcelFile(r"C:\Users\shres\Downloads\TUFTS.xlsx")
sheet_name = xls.sheet_names[0]  # Assuming you want the first sheet's name

# Create a DataFrame with the existing columns of filtered_df
sheet_name_df = pd.DataFrame(columns=filtered_df.columns)

# Append the sheet name as the first row to the DataFrame
sheet_name_df.loc[0] = sheet_name

# Concatenate the sheet name DataFrame with the filtered_df DataFrame
filtered_df = pd.concat([sheet_name_df, filtered_df], ignore_index=True)

# Display the modified DataFrame with the sheet name as the first row
filtered_df

0   Greater Noida Mental MNS0000192      Greater Noida Mental MNS0000192
1                          1/1/2024                       EFFECTIVE DATE
2                          1/1/2024
3                       COMMISSION                            $31.00 PEM
4               SUBJECT TO MED U/W                               ___ YES
5                         OPTION 1                              OPTION 1
6                PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
7                     Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
8             In Network Copays PCP                             $10/ $10
9             In Network Copays SPC                             $25/ $25
10             In Network Copays UC                                  $10
11             In Network Copays ER                                 $230
12         In Net Ded/Coins/OOP Ded                $5,000/ $10,000 (Emb)
13       In Net Ded/Coins/OOP Coins                                  80%
14         In Net Ded/Coins/OOP OOP                      $6,000/ $12,000
15               Out of Network Ded                                  N/A
16             Out of Network Coins                                  N/A
17               Out of Network OOP                                  N/A
18                        OPTION 2                              OPTION 2
19               PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
20                    Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
21            In Network Copays PCP                             $20/ $20
22            In Network Copays SPC                             $35/ $35
23             In Network Copays UC                                  $20
24             In Network Copays ER                                 $330
25         In Net Ded/Coins/OOP Ded                $6,000/ $12,000 (Emb)
26       In Net Ded/Coins/OOP Coins                                  90%
27         In Net Ded/Coins/OOP OOP                      $7,000/ $12,000
28               Out of Network Ded                                  N/A
29             Out of Network Coins                                  N/A
30               Out of Network OOP                                  N/A

In [20]:
filtered_df.iloc[0, 1] = np.nan  # or None

filtered_df

0   Greater Noida Mental MNS0000192                                  NaN
1                   EFFECTIVE DATE                              1/1/2024
2                ACCOUNT EXECUTIVE                        Bryan Cranston
3                     UNDERWRITER                           Kristen Bell
4                       COMMISSION                            $31.00 PEM
5               SUBJECT TO MED U/W                               ___ YES
6                         OPTION 1                              OPTION 1
7                PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
8                     Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
9             In Network Copays PCP                             $10/ $10
10            In Network Copays SPC                             $25/ $25
11             In Network Copays UC                                  $10
12             In Network Copays ER                                 $230
13         In Net Ded/Coins/OOP Ded                $5,000/ $10,000 (Emb)
14       In Net Ded/Coins/OOP Coins                                  80%
15         In Net Ded/Coins/OOP OOP                      $6,000/ $12,000
16               Out of Network Ded                                  N/A
17             Out of Network Coins                                  N/A
18               Out of Network OOP                                  N/A
19                        OPTION 2                              OPTION 2
20               PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
21                    Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
22            In Network Copays PCP                             $20/ $20
23            In Network Copays SPC                             $35/ $35
24             In Network Copays UC                                  $20
25             In Network Copays ER                                 $330
26         In Net Ded/Coins/OOP Ded                $6,000/ $12,000 (Emb)
27       In Net Ded/Coins/OOP Coins                                  90%
28         In Net Ded/Coins/OOP OOP                      $7,000/ $12,000
29               Out of Network Ded                                  N/A
30             Out of Network Coins                                  N/A
31               Out of Network OOP                                  N/A

In [21]:
# Assuming filtered_df is your DataFrame

# Get the value of the first row in the first column
first_cell_value = filtered_df.iloc[0, 0]

# Find the index of "MNS"
index_of_MNS = first_cell_value.find("MNS")

# Split the string into two parts based on the index of "MNS"
before_MNS = first_cell_value[:index_of_MNS]
including_after_MNS = first_cell_value[index_of_MNS:]

# Create two new rows with split values
new_row_before = filtered_df.iloc[0].copy()
new_row_before[0] = before_MNS

new_row_after = filtered_df.iloc[0].copy()
new_row_after[0] = including_after_MNS

# Insert new rows into the DataFrame
filtered_df.loc[1] = pd.Series(new_row_before)
filtered_df.loc[2] = pd.Series(new_row_after)

# Drop the original row
filtered_df.drop(0, inplace=True)

# Reset index
filtered_df.reset_index(drop=True, inplace=True)


# Display the updated DataFrame
filtered_df

0        Greater Noida Mental                                   NaN
1                   MNS0000192                                  NaN
2                UNDERWRITER                           Kristen Bell
3                  COMMISSION                            $31.00 PEM
4          SUBJECT TO MED U/W                               ___ YES
5                    OPTION 1                              OPTION 1
6           PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
7                Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
8        In Network Copays PCP                             $10/ $10
9        In Network Copays SPC                             $25/ $25
10        In Network Copays UC                                  $10
11        In Network Copays ER                                 $230
12    In Net Ded/Coins/OOP Ded                $5,000/ $10,000 (Emb)
13  In Net Ded/Coins/OOP Coins                                  80%
14    In Net Ded/Coins/OOP OOP                      $6,000/ $12,000
15          Out of Network Ded                                  N/A
16        Out of Network Coins                                  N/A
17          Out of Network OOP                                  N/A
18                   OPTION 2                              OPTION 2
19          PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
20               Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
21       In Network Copays PCP                             $20/ $20
22       In Network Copays SPC                             $35/ $35
23        In Network Copays UC                                  $20
24        In Network Copays ER                                 $330
25    In Net Ded/Coins/OOP Ded                $6,000/ $12,000 (Emb)
26  In Net Ded/Coins/OOP Coins                                  90%
27    In Net Ded/Coins/OOP OOP                      $7,000/ $12,000
28          Out of Network Ded                                  N/A
29        Out of Network Coins                                  N/A
30          Out of Network OOP                                  N/A

In [22]:
# Swap values: 1st row in the 1st column with 1st row in the 2nd column
temp = filtered_df.iloc[0, 0]
filtered_df.iloc[0, 0] = filtered_df.iloc[0, 1]
filtered_df.iloc[0, 1] = temp

# Swap values: 2nd row in the 1st column with 2nd row in the 2nd column
temp = filtered_df.iloc[1, 0]
filtered_df.iloc[1, 0] = filtered_df.iloc[1, 1]
filtered_df.iloc[1, 1] = temp

filtered_df

0                          NaN                Greater Noida Mental
1                          NaN                           MNS0000192
2                UNDERWRITER                           Kristen Bell
3                  COMMISSION                            $31.00 PEM
4          SUBJECT TO MED U/W                               ___ YES
5                    OPTION 1                              OPTION 1
6           PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
7                Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
8        In Network Copays PCP                             $10/ $10
9        In Network Copays SPC                             $25/ $25
10        In Network Copays UC                                  $10
11        In Network Copays ER                                 $230
12    In Net Ded/Coins/OOP Ded                $5,000/ $10,000 (Emb)
13  In Net Ded/Coins/OOP Coins                                  80%
14    In Net Ded/Coins/OOP OOP                      $6,000/ $12,000
15          Out of Network Ded                                  N/A
16        Out of Network Coins                                  N/A
17          Out of Network OOP                                  N/A
18                   OPTION 2                              OPTION 2
19          PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
20               Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
21       In Network Copays PCP                             $20/ $20
22       In Network Copays SPC                             $35/ $35
23        In Network Copays UC                                  $20
24        In Network Copays ER                                 $330
25    In Net Ded/Coins/OOP Ded                $6,000/ $12,000 (Emb)
26  In Net Ded/Coins/OOP Coins                                  90%
27    In Net Ded/Coins/OOP OOP                      $7,000/ $12,000
28          Out of Network Ded                                  N/A
29        Out of Network Coins                                  N/A
30          Out of Network OOP                                  N/A

In [23]:
# Fill the first NaN value in the first column with 'Group Name'
filtered_df.iloc[:, 0] = filtered_df.iloc[:, 0].fillna('Group Name', limit=1)

# Fill the second NaN value in the first column with 'MNS ID'
filtered_df.iloc[:, 0] = filtered_df.iloc[:, 0].fillna('MNS ID', limit=1)
filtered_df

0                   Group Name                Greater Noida Mental
1                       MNS ID                           MNS0000192
2                UNDERWRITER                           Kristen Bell
3                  COMMISSION                            $31.00 PEM
4          SUBJECT TO MED U/W                               ___ YES
5                    OPTION 1                              OPTION 1
6           PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
7                Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
8        In Network Copays PCP                             $10/ $10
9        In Network Copays SPC                             $25/ $25
10        In Network Copays UC                                  $10
11        In Network Copays ER                                 $230
12    In Net Ded/Coins/OOP Ded                $5,000/ $10,000 (Emb)
13  In Net Ded/Coins/OOP Coins                                  80%
14    In Net Ded/Coins/OOP OOP                      $6,000/ $12,000
15          Out of Network Ded                                  N/A
16        Out of Network Coins                                  N/A
17          Out of Network OOP                                  N/A
18                   OPTION 2                              OPTION 2
19          PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
20               Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
21       In Network Copays PCP                             $20/ $20
22       In Network Copays SPC                             $35/ $35
23        In Network Copays UC                                  $20
24        In Network Copays ER                                 $330
25    In Net Ded/Coins/OOP Ded                $6,000/ $12,000 (Emb)
26  In Net Ded/Coins/OOP Coins                                  90%
27    In Net Ded/Coins/OOP OOP                      $7,000/ $12,000
28          Out of Network Ded                                  N/A
29        Out of Network Coins                                  N/A
30          Out of Network OOP                                  N/A

In [24]:
# Row mapping dictionary
word_mapping = {
    'In Network Copays PCP': 'INN PCP COPAY',
    'In Network Copays SPC': 'INN SPEC COPAY',
    'In Network Copays UC': 'INN URGENT CARE COPAY',
    'In Network Copays ER': 'INN ER COPAY',
    'In Net Ded/Coins/OOP Ded': 'INN DEDUCTIBLE',
    'In Net Ded/Coins/OOP Coins': 'INN COINSURANCE',
    'In Net Ded/Coins/OOP OOP': 'INN OOP Max.',
    'Out of Network Ded': 'OON DEDUCTIBLE',
    'Out of Network Coins': 'OON COINSURANCE',
    'Out of Network OOP': 'OON OOP Max.'
}

# Replace words in the DataFrame using the mapping dictionary
filtered_df.replace(word_mapping, inplace=True)

filtered_df

0              Group Name                Greater Noida Mental
1                  MNS ID                           MNS0000192
2           UNDERWRITER                           Kristen Bell
3             COMMISSION                            $31.00 PEM
4     SUBJECT TO MED U/W                               ___ YES
5               OPTION 1                              OPTION 1
6      PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
7           Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
8           INN PCP COPAY                             $10/ $10
9          INN SPEC COPAY                             $25/ $25
10  INN URGENT CARE COPAY                                  $10
11           INN ER COPAY                                 $230
12         INN DEDUCTIBLE                $5,000/ $10,000 (Emb)
13        INN COINSURANCE                                  80%
14           INN OOP Max.                      $6,000/ $12,000
15         OON DEDUCTIBLE                                  N/A
16        OON COINSURANCE                                  N/A
17           OON OOP Max.                                  N/A
18              OPTION 2                              OPTION 2
19     PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
20          Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
21          INN PCP COPAY                             $20/ $20
22         INN SPEC COPAY                             $35/ $35
23  INN URGENT CARE COPAY                                  $20
24           INN ER COPAY                                 $330
25         INN DEDUCTIBLE                $6,000/ $12,000 (Emb)
26        INN COINSURANCE                                  90%
27           INN OOP Max.                      $7,000/ $12,000
28         OON DEDUCTIBLE                                  N/A
29        OON COINSURANCE                                  N/A
30           OON OOP Max.                                  N/A

In [26]:
# Create a new DataFrame to store the result
new_df = pd.DataFrame(columns=filtered_df.columns)

# Iterate over each row in the original DataFrame
for index, row in filtered_df.iterrows():
    # Check if the row in the second column contains '/'
    if '/' in row[1]:  # Assuming the second column is the one you want to check
        # Split the row into two rows if '/' has '$' before or after it
        parts = row[1].split('/')
        if ('$' in parts[0]) or ('$' in parts[1]):
            # Add 'IND' prefix to the first split row and 'FAM' to the second split row if necessary
            new_df.loc[len(new_df)] = ['IND ' + row[0], parts[0]]
            new_df.loc[len(new_df)] = ['FAM ' + row[0], parts[1]]
        else:
            new_df.loc[len(new_df)] = [row[0], row[1]]
    else:
        # If no '/', append the row as it is to the new DataFrame
        new_df.loc[len(new_df)] = [row[0], row[1]]

print(new_df)

0              Group Name                Greater Noida Mental
1                  MNS ID                           MNS0000192
2           UNDERWRITER                           Kristen Bell
3             COMMISSION                            $31.00 PEM
4     SUBJECT TO MED U/W                               ___ YES
5               OPTION 1                              OPTION 1
6      PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
7           Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
8       IND INN PCP COPAY                                  $10
9       FAM INN PCP COPAY                                  $10
10     IND INN SPEC COPAY                                  $25
11     FAM INN SPEC COPAY                                  $25
12  INN URGENT CARE COPAY                                  $10
13           INN ER COPAY                                 $230
14     IND INN DEDUCTIBLE                               $5,000
15     FAM INN DEDUCTIBLE                        $10,000 (Emb)
16        INN COINSURANCE                                  80%
17       IND INN OOP Max.                               $6,000
18       FAM INN OOP Max.                              $12,000
19         OON DEDUCTIBLE                                  N/A
20        OON COINSURANCE                                  N/A
21           OON OOP Max.                                  N/A
22              OPTION 2                              OPTION 2
23     PRIMARY/SOLD PLAN                     PRIMARY/SOLD PLAN
24          Benefit Plan   CPIJ Mod (Granite Advantage EPO OA)
25      IND INN PCP COPAY                                  $20
26      FAM INN PCP COPAY                                  $20
27     IND INN SPEC COPAY                                  $35
28     FAM INN SPEC COPAY                                  $35
29  INN URGENT CARE COPAY                                  $20
30           INN ER COPAY                                 $330
31     IND INN DEDUCTIBLE                               $6,000
32     FAM INN DEDUCTIBLE                        $12,000 (Emb)
33        INN COINSURANCE                                  90%
34       IND INN OOP Max.                               $7,000
35       FAM INN OOP Max.                              $12,000
36         OON DEDUCTIBLE                                  N/A
37        OON COINSURANCE                                  N/A
38           OON OOP Max.                                  N/A